#!/bin/bash
# description: cpu_recorder, just record 2 days for now. 
# save the records in the RECORDS_FILE by using sar.
# Check: ps -e|grep cpu_recorder.
EXEC_PATH=/home/seven0vm/Code
EXEC=cpu_recorder
PID_FILE=/var/run/cpu_recorder.pid
DAEMON=/home/seven0vm/Code/cpu_recorder
RECORDS_FILE=/home/seven0vm/Code/records.log


if ! [ -x $EXEC_PATH/$EXEC ] ; then
    echo "ERROR: $EXEC_PATH/$EXEC not found"
    exit 1
fi

# check sar is installed.
sar -u &> tmp
if [ $? = "0" ];then
	echo "Load preconditions successfully..."
	rm tmp
else
	echo "This program needs sar package in the sysstat or others..."
	echo "So please install the sysstat package."
	exit 1
fi

stop()
{
    echo "Stoping $EXEC ..."
    killall $DAEMON > /dev/null
    usleep 100
    echo "Shutting down $EXEC: [ OK ]"
    
}

start()
{
    echo "Starting $EXEC ..."
    if [ -e $RECORDS_FILE ];then
    	$DAEMON > /dev/null 
    	sleep 1
    	echo "Starting $EXEC: [ OK ]"
    else
    	echo "ERROR!"
    fi
}

restart()
{
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status -p $PID_FILE $DAEMON
    ;;
    *)
        echo "Usage: service $EXEC {start|stop|restart|status}"
        exit 1
esac
exit $?